{{!
    這裡可以放註解
}}
{
        {{#_source}}
        "_source": {{#toJson}}_source{{/toJson}},
        {{/_source}}
        {{^search_after}}
        {{#from}}
        "from": "{{from}}{{^from}}0{{/from}}",
        {{/from}}
        {{/search_after}}
        "size": "{{size}}{{^size}}10{{/size}}",
        "min_score": "{{min_score}}{{^min_score}}0.5{{/min_score}}",
        "query": {
            "match": {
                "phonetic": {
                    "query": "{{query}}",
                    "fuzziness": "{{fuziness}}{{^fuzziness}}3{{/fuzziness}}"
                }
            }
        }
}
