{{!
    這裡可以放註解
}}
{
        {{#_source}}
        "_source": {{#toJson}}_source{{/toJson}},
        {{/_source}}
        {{^search_after}}
        {{#from}}
        "from": "{{from}}{{^from}}0{{/from}}",
        {{/from}}
        {{/search_after}}
        "size": "{{size}}{{^size}}10{{/size}}"
        {{#query}}
        ,
        "query": {
            "match": {
                "words": {
                    "query": "{{query}}"                }
            }
        }
        {{/query}}
}
