gosearch:
  elasticSearch:
  #  host: '172.25.10.2'
  #  port: 30807
  #  host: '10.100.80.119'
  #  host: '127.0.0.1'
    host: "elasticsearch-1-elastic-vm-0"
    port: 9200
  db:
    dsn: 'mysql:host=127.0.0.1;port=3306;dbname=gosearch'
    user: 'root'
    password: 'kJgKKFEfnasO5BnSb9zg'
  redis:
    host: '127.0.0.1'
    port: 6379
    db: 0
    lifetime: 360
  ldap:
    host:  "172.26.2.3"
    username: "cn=ldapreader,cn=users,dc=hq,dc=hiiir"
    password: "&ujm8ik,"
    basedn: "ou=here,dc=hq,dc=hiiir"
  http:
    port: 8090

