gosearch:
  lang:
    title: Go Search
    logo:
      mini: g
      site: Go
      title: Search
    login:
      title: 登入
      message: 請使用員工帳號登入
    error:
      message: 看來您遇到問題了喔
    account: 帳號
    password: 密碼
    button:
      login: 登入
      logout: 登出
      register: 註冊
    togglenav: Toggle navigation
    sidebar:
      index: 索引
      search: 搜尋
      hotwords: 熱門關鍵字
      badword: 排除關鍵字
      admin:
        title: 管理
        project: 專案管理
        user: 帳號管理 
        system: 系統管理 
    menu:
      choice_project: 請選擇專案
      create_project: 建立新專案
