CREATE DATABASE  IF NOT EXISTS gosearch DEFAULT CHARSET=utf8;
use gosearch;
CREATE TABLE IF NOT EXISTS `user` (
  `account` VARCHAR(64) NOT NULL,
  `name` VARCHAR(32) NOT NULL COMMENT '員工名稱',
  `level` TINYINT NOT NULL DEFAULT 0,
  `createTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updateTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`account`))
ENGINE = InnoDB DEFAULT CHARSET=utf8;
